FROM php:5.6-apache
RUN docker-php-ext-install mysqli pdo pdo_mysql
RUN apt-get update && apt-get install -y libmcrypt-dev
RUN docker-php-ext-install mcrypt
RUN a2enmod rewrite
COPY vhost.conf /etc/apache2/sites-available/000-default.conf
RUN apt-get install -y libzip-dev zip && docker-php-ext-install zip
COPY php.ini /usr/local/etc/php/php.ini